### ISSUE TITLE
pep8speaks is not getting updated

### ISSUE THREAD

**Issue by chkoar** [pep8speaks-org/pep8speaks#178]
Hey,

Can you help us [here](https://github.com/scikit-learn-contrib/imbalanced-learn/pull/722)? Are we missing something? 
We made several changes but pep8speaks does not seem to respond anymore.

**Comment by OrkoHunter** [comment]
Hello!

Thank you for creating the issue. I manually resent a payload for this PR and the bot has updated its comment. I can see that the `.pep8speaks.yml` of the master branch is being used (88 chars max line length instead of 79).

<img width="934" alt="Screenshot 2020-06-29 at 8 52 04 PM" src="https://user-images.githubusercontent.com/8065913/86001794-64d13580-ba4a-11ea-8420-9a35e64116fb.png">

I wonder there are two issues here -
1. Perhaps the app has been uninstalled from the repo/org. You can take a look at the settings.
2. The PR has touched 83 files and the bot needs to fetch each file and run the linter on them. Maybe it took a lot of time and the request timed out. Created https://github.com/OrkoHunter/pep8speaks/issues/179 to improve architecture.

Feel free to comment here if I need to force refresh the bot's comment. Thanks!

**Comment by chkoar** [comment]
Great thanks.
