### ISSUE TITLE
Highlight only errors

### ISSUE THREAD

**Issue by glemaitre** [pep8speaks-org/pep8speaks#25]
I am currently using pep8speaks for the `imbalanced-learn` project.
When dealing PR which lead to large changes (e.g. [here](https://github.com/scikit-learn-contrib/imbalanced-learn/pull/242)), it starts to be challenging to spot the errors among all messages.

It could be nice to have an option to actually print the file with errors since that usually, developers are not that much interested about things that are fine while reviewing PR.

What do you think?

**Comment by OrkoHunter** [comment]
Hey Guillaume, I'm thankful to you for using PEP8Speaks.

I see the point and I too feel a need to have an alternative. My initial aim of mentioning `no errors in abc file` was for the reviewer to make sure that the file has indeed been checked. But as I perceive, another expected behavior from the bot would be

 - Mention only the files with issues.
 - After update, if there are no errors, simply write a one-liner saying everything is OK.

Is this good? If yes, I'll try to implement it right away. :)

**Comment by glemaitre** [comment]
Yep that's seems great

**Comment by OrkoHunter** [comment]
@glemaitre Please let me know about your opinion on #26

**Comment by glemaitre** [comment]
This seems good
